//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketTable
    {
        public int Ticket_Id { get; set; }
        public string CreatedBy { get; set; }
        public string Remarks { get; set; }
        public string Subject { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<System.DateTime> DataTime { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Dep_ID { get; set; }
        public string Dept_List { get; set; }
    }
}
